[CIVP-19308] New civis_file_to_table
zacharydfriedlander/civis-python pull request #2
Opened 2019-09-25 20:41 UTC by zacharydfriedlander

2019-10-01 22:29 UTC, jkulzick requested changes

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +def civis_file_to_table(file_id_or_ids, database, table, client=None,
Why not just `file_ids`? `file_id_or_ids` is longer and is still ambiguous, meaning i'm still going to scratch my head and look at the docstring.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +                        escaped=False, execution="delayed",
I think `execution` should default to `immediate` because it is the default behavior that users will expect and actually having the default be `delayed` could be considered a breaking change since the behavior of syncing column statistics would no longer be blocking.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +                        compression=None,
I don't think we actually need this parameter. I think it just complicates the interface. The file cleaner endpoint will tell us what the compression is.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +        A list of the primary key column(s) of the destination table. If the
I think the criteria is not that the table exists, but that the table exists and the primary keys have been defined on the table. And that said, I think that is minutiae that is likely to just confuse users. I would be okay with just saying `If the import mode is "upsert", this field is required.`.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +    last_modified_keys: list[str], optional
Same comment as `primary_keys`

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +        One of "delayed" and "immediate". if "immediate", refresh column
A couple small typos: `One of "delayed" _or_ "immediate". _I_f "immediate", refresh ... `

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +        deferred statistics update; column statistics may not be available
Another possible wording: `If "delayed", delay the refresh of column statistics for up to 24 hours.`

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +        until the next day. In addition, if existing_table_rows is "upsert",
We should probably stay consistent with how we refer to `"upsert"`. So either stick with referencing `existing_table_rows` or use the term `import mode`. I'm leaning towards the former.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +    compression: strip, optional
Per the above comment, I would remove this

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +                                           output_file.name,
IMHO `output_file.name` will not be that helpful to the user or support. We should at least have the file id.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +            table_columns = table_columns or file_columns
I think this might be easier to understand if we separate the validation of the first `cleaning_futures` result from the others. It took me awhile to understand that the setting and processing of the various attributes differed (e.g., `headers` vs `table_columns`).

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +            if table_columns != file_columns:
It seems like this should be converted to a utility function that compares two variables and raises the error if they don't match. Then we could call it for all of the below attributes we care about.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +    # Use Preprocess endpoint to get the table columns
Should we move preprocessing to a private function? It would help with readability and unit testing.

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +                raise CivisImportError('Mismatch between detected schemas:\n'
Should we add something to the error message like `'All files must have the same format. Mismatch ...'`?

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +        if delimiter != detected_info['columnDelimiter']:
`delimiter` can also be passed in like `headers` so we should be consistent

2019-10-01 22:29 UTC, jkulzick commented on civis/io/_tables.py
> +            detect_table_columns=(not table_exists
It looks like we reference these conditions twice (i.e., `not table_exists or existing_table_rows == 'drop'`). Perhaps we should encapsulate these conditions into a well-named variable, such as `table_columns_required` or `specify_table_columns`.

2019-10-02 16:09 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +                        compression=None,
Removed.

2019-10-02 16:10 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +        A list of the primary key column(s) of the destination table. If the
I initially had copied this wording from the API docs - I've updated it for `primary_keys` and `last_modified_keys`.

2019-10-02 16:10 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +        One of "delayed" and "immediate". if "immediate", refresh column
Fixed.

2019-10-02 16:10 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +    compression: strip, optional
Removed

2019-10-02 16:11 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +            detect_table_columns=(not table_exists
Refactored.

2019-10-02 16:33 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +        if delimiter != detected_info['columnDelimiter']:
This had been set up in this way because `delimiter` has some validation set on it above. I've changed that validation to only apply if `delimiter` is passed in, and made the checking consistent here.

2019-10-02 16:34 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +                                           output_file.name,
Changed to use ids

2019-10-02 16:34 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +        until the next day. In addition, if existing_table_rows is "upsert",
Agreed. Rephrased.

2019-10-02 16:34 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +        deferred statistics update; column statistics may not be available
Rephrased.

2019-10-02 16:39 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +                        escaped=False, execution="delayed",
That seems reasonable. I had selected `delayed` as the default in order to match the API.

2019-10-02 18:29 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +                raise CivisImportError('Mismatch between detected schemas:\n'
Reworded

2019-10-02 18:29 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +            if table_columns != file_columns:
That seems like needless indirection IMO - I think I'd rather do all of this inline.

2019-10-02 18:41 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +            table_columns = table_columns or file_columns
The benefit of taking all the futures at once, and raising even on the first future, is that we get to catch inconsistencies between what the user has asked of us via provided parameters and the file the user has given us. I guess my question then is whether or not we trust our users.

2019-10-02 18:43 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +def civis_file_to_table(file_id_or_ids, database, table, client=None,
Renamed.

2019-10-02 21:08 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +    # Use Preprocess endpoint to get the table columns
Done

2019-10-02 21:10 UTC, zacharydfriedlander commented
I'm pretty sure something is off about how I've updated the cassettes - i've reverted those changes for now, and I'm going to keep investigating that.

2019-10-10 20:14 UTC, zacharydfriedlander commented
So it looks like these tests are failing due to not having a real API key (and therefore being unable to construct an API client?)

2019-10-10 22:07 UTC, zacharydfriedlander commented
So according to a `git bisect`, [` a7ce5bf16c84b68ac1ba40fa407c2df555067a44`](https://github.com/zacharydfriedlander/civis-python/commit/a7ce5bf16c84b68ac1ba40fa407c2df555067a44) is the bad commit.

I've done some more experimentation, and it looks like the issue occurs if _any_ `setUp` method is defined, even a blank one. Why this is the case, I have no idea.

2019-10-14 20:21 UTC, jkulzick requested changes

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +def _replace_nulls(column_list):
I think a more explicit name would be good. Perhaps something like `_replace_null_column_names`

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +    if need_table_columns:
Perhaps move the default assignment here from line 1185 as well so the context is not spread out

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +    if compression is None:
Same comment as `table_columns`

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +            file_columns = _replace_nulls(detected_info['tableColumns'])
Another approach would be to only call `_replace_nulls` at the end after validating all of the futures

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +            if table_columns != file_columns:
I find the code for these comparisons to be a bit repetitive. The benefit is that you can highly customize the error message (although you could pass in an error message prefix to some common function) and the downside is that there is more code to maintain. I don't have any strong opinions either way.

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +    if headers is None:
Strictly speaking following the validation laid out we would need to validate both `headers` and `delimiter` in the first completed job against the values provided when they are provided.

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +    assert len(done) == 1
I'm curious why this is here? If we are not confident that `concurrent.futures.FIRST_COMPLETED` works should we use something else?

2019-10-14 20:21 UTC, jkulzick commented on civis/tests/test_io.py
> +    def test_process_cleaning_results(self, _m_get_api_spec):
We should probably have some tests that cover the scenarios when we raise a `CivisImportError`

2019-10-14 20:21 UTC, jkulzick commented on civis/io/_tables.py
> +            raise CivisImportError('Mismatch between detected headers - '
There are slightly different amounts of information in all 4 of these error messages. In `table_columns` and `delimiter` the expected and actual results are provided along with the offending file id. In `headers` and `compression` these details are not provided.

2019-10-18 16:29 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +            if table_columns != file_columns:
I don't mind the repetition, and I'd rather reduce the amount of indirection needed to understand what's happening or where an error comes from.

2019-10-18 16:49 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +            raise CivisImportError('Mismatch between detected headers - '
Added for `compression`. However, for headers the exact phrasing IMO is harder because it's a boolean. Open to suggestions for how best to word that error.

2019-10-18 16:49 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +    assert len(done) == 1
I think I had this here as a guard more against Platform completing two jobs at the same time than against `concurrent.futures.wait`. However, I think the odds of that happening (especially in any sort of reproducible way) are slim. Removed.

2019-10-18 16:49 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +    if headers is None:
Added

2019-10-18 16:49 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +            file_columns = _replace_nulls(detected_info['tableColumns'])
Done

2019-10-18 16:51 UTC, zacharydfriedlander commented on civis/io/_tables.py
> +    if compression is None:
That first initialization was entirely unnecessary - removed.

2019-10-18 20:24 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +    def test_process_cleaning_results(self, _m_get_api_spec):
Added

2019-10-18 21:13 UTC, jkulzick approved these changes
LGTM

2019-10-21 13:49 UTC, zacharydfriedlander commented
So it looks like there's an issue with multi-file uploads where `concurrent.futures.wait` will return more than one future in the `done` tuple on that `FIRST_COMPLETED` setting. I am going to refactor that code to be able to account for it.

2019-10-21 17:12 UTC, jkulzick approved these changes
LGTM

2019-10-21 17:53 UTC, merged