[CIVP-19155] IO cassette tests to mocks
zacharydfriedlander/civis-python pull request #3
Opened 2019-10-03 15:51 UTC by zacharydfriedlander

In this PR, we've changed the tests for the following functions from using cassettes to use a mocked client, or mocking in general:

* dataframe_to_civis
* csv_to_civis
* civis_file_to_table

We've also added `pytest.mark`s to all of the tests indicating which function is under test; this will allow us to run only the tests we care about using `pytest -k <function>`.

2019-10-04 20:40 UTC, zacharydfriedlander commented
@jkulzick bump

2019-10-05 13:51 UTC, jkulzick requested changes
@zacharydfriedlander Nice work! This is already a big improvement on these tests. I tried to review these tests as if they were written from scratch. That said, I know the scope of this PR was not to fix the current tests but to implement them without the use of VCR so I just want to reiterate here that I'm comfortable if we track most of the feedback as TODO comments in the code to be fixed later. If there is something relatively easy to fix now then it would be great if we did that.

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        cls.mock_client = create_client_mock()
I think it would be good to move this to line 61 just from a readability standpoint

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +    @pytest.mark.file_to_civis
🔥

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        cls.mock_client = create_client_mock()
Also these couple comments are outside the scope of this PR, but leaving them here for posterity.
1. I'm confused why we are using both `setUpClass` and `setup_class`. As far as I can tell they are different syntax for performing class level setup.
2. The fact that `@mock.patch(api_import_str, return_value=civis_api_spec)` is defined above each test function is a bit of a code smell to me. If its trully patched in every test then it ought to be patched in the setup or as part of a fixture with `autouse=true`.

Once again, I don't think you need to do anything with either of these comments.

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +    @mock.patch('civis.io._tables.file_to_civis')
👏 Keeping the unit test of `csv_to_civis` focused on the scope of `csv_to_civis`. Nice job!

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        with TemporaryDirectory() as tmpdir:
We should probably be using [mock_open](https://docs.python.org/3/library/unittest.mock.html#mock-open) instead. That would also negate the need for using `mock.ANY` below.

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        civis.io.civis_file_to_table(self.file_id, database, table,
I think `self.file_id` is set above in `setup_class` using the VCR cassette? Should we remove that dependency for this test since we transitioned away from VCR?

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        assert call_kwargs['source']['file']['id'] == self.file_id
I think it would be better to just asset `call_kwargs` in its entirety. I know its a pain to hard-code the entire expected response but that feels like the proper way to do things. As it stands right now there is no way to ensure that `source` only has `file` or `file` only has `id`, etc.

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        assert call_kwargs['client'] == self.mock_client
See comment below around asserting `call_kwargs`

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        self.mock_client.jobs.post_runs.assert_called_once_with(mock_import_id)
We should also be mocking `CivisFuture` and asserting that it is called with the appropriate values and that the return value of `civis_file_to_table` is said expected mock instance. I guess i'm okay if we consider that out of scope for this PR. Just noting here.

Same comment applies to `csv_to_civis` test above. We don't verify the return value.

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
>          df = pd.DataFrame([['1', '2', '3']], columns=['a', 'b', 'c'])
wondering if we should be mocking out `df.to_csv` and asserting how that is called. once again i'm fine with this being outside the scope of this PR. maybe we should leave a TODO?

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        self.mock_client.jobs.post_runs.assert_called_once_with(mock_import_id)
Maybe we can just leave some TODOs?

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        assert m_file_to_civis.call_count == 1
We should also validate the args. I think this would be feasible if we were using `mock_open`. Once again, I'm comfortable leaving a TODO here as well.

2019-10-05 13:51 UTC, jkulzick commented on civis/tests/test_io.py
> +        assert call_kwargs['client'] == self.mock_client
I think we should be validating all `call_kwargs` similar to the comment above

2019-10-05 13:52 UTC, jkulzick commented
![image](https://user-images.githubusercontent.com/4155284/66255780-67b62880-e74d-11e9-80a7-17380b46f0cf.png)

![5nsiFjdgylfK3csZ5T](https://media2.giphy.com/media/5nsiFjdgylfK3csZ5T/giphy.gif?cid=e1bb72ff6c0e129ac8aaf858c4bae6f5c92b693cfed62245&rid=giphy.gif)

2019-10-07 14:20 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        with TemporaryDirectory() as tmpdir:
`mock_open` was causing some issues in Python 3.4, which is why I adopted this pattern instead.

The real problem is that the client is testing on Python 3.4, which has been [end of life for nearly 6 months now](python.org/downloads/release/python-3410/). However, removing that support is decidedly outside the scope of these changes.

2019-10-07 14:24 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        cls.mock_client = create_client_mock()
1. I've combined `setUpClass` and `setup_class` into a single `setUpClass`. 
2. I'm confused about this as well, since the mock does also exist at the class level...

2019-10-07 14:46 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        assert call_kwargs['source']['file']['id'] == self.file_id
Part of why I had avoided doing so was because so many of these kwargs would just be defaults. However, I agree that the test is worth adding to make sure everything is passed as expected.

2019-10-07 15:01 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        civis.io.civis_file_to_table(self.file_id, database, table,
Good catch - removed.

2019-10-07 15:22 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        with TemporaryDirectory() as tmpdir:
Update here: I was able to get `mock_open` working in python 3.4 by using `patch.object` instead of plain `patch`, and adding a `create=True` since open is a built-in. See [this SO post](https://stackoverflow.com/questions/31705057/attributeerror-module-main-from-does-not-have-the-attribute-open).

2019-10-07 17:56 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        self.mock_client.jobs.post_runs.assert_called_once_with(mock_import_id)
Added steps to check return values of our functions.

2019-10-07 21:39 UTC, jkulzick commented on civis/tests/test_io.py
> +        cls.mock_client = create_client_mock()
Can you move line 97 up to at least above line 60? I found it hard to read due since the context for the VCR on line 60 is so long

2019-10-07 21:47 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        cls.mock_client = create_client_mock()
Moved.

2019-10-07 21:49 UTC, jkulzick requested changes

2019-10-07 21:49 UTC, jkulzick commented on civis/tests/test_io.py
> +        result.set_result({'state': 'success'})
Why do we need this?

2019-10-07 21:49 UTC, jkulzick commented on civis/tests/test_io.py
> +        assert isinstance(result, civis.futures.CivisFuture)
Can we do something like what was done below here as well?:
```
mock_future = mock.create_autospec(civis.futures.CivisFuture, spec_set=True)
self.mock_client.jobs.get_runs.return_value = mock_future
```

2019-10-08 13:56 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        result.set_result({'state': 'success'})
I don't think we do. Removed.

2019-10-08 13:56 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +        assert isinstance(result, civis.futures.CivisFuture)
Refactored to mock out `CivisFuture` construction and make assertions on the constructor call.

2019-10-08 15:42 UTC, jkulzick requested changes

2019-10-08 15:42 UTC, jkulzick commented on civis/tests/test_io.py
> +            civis.io.civis_file_to_table(
Can we also test the return value of `civis_file_to_table`?

2019-10-08 15:59 UTC, zacharydfriedlander commented on civis/tests/test_io.py
> +            civis.io.civis_file_to_table(
IMO We are already doing so by testing the call to `CivisFuture` - however, I have added a sentinel check to assert that the constructed future is in fact returned.

2019-10-08 17:05 UTC, jkulzick approved these changes
LGTM

2019-10-08 17:05 UTC, jkulzick commented on civis/tests/test_io.py
> +            m_future.return_value = mock.sentinel.a_future
![share-very-discover-10uEX5kfeodYgo](https://media1.giphy.com/media/10uEX5kfeodYgo/giphy.gif?cid=e1bb72ff8f5f9ff360607a945717df736c19c88a86b2fefd&rid=giphy.gif)

2019-10-08 17:56 UTC, merged