[CIVP-19310] Expose more new params
zacharydfriedlander/civis-python pull request #5
Opened 2019-10-21 18:07 UTC by zacharydfriedlander

Add new params from `civis_file_to_table` to `dataframe_to_civis` and `csv_to_civis`.

2019-10-21 18:46 UTC, jkulzick requested changes

2019-10-21 18:46 UTC, jkulzick commented on civis/io/_tables.py
> +                       primary_keys=None, last_modified_keys=None,
We should add these to the docstring as well

2019-10-21 18:46 UTC, jkulzick commented on civis/io/_tables.py
> +                 primary_keys=None, last_modified_keys=None,
We should add these to the docstring as well

2019-10-21 20:21 UTC, jkulzick approved these changes
LGTM %Travis

2019-10-22 15:09 UTC, zacharydfriedlander commented
So that other travis job has finished (and is green) but for some reason Github didn't get the memo here. Merging.

2019-10-22 15:09 UTC, merged